# Generated by Django 5.0.2 on 2024-03-02 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoodie',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='hoodie',
            name='category',
        ),
        migrations.AddField(
            model_name='hoodie',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hoodie',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='hoodie',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hoodie',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hoodie',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hoodie',
            name='avaiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hoodie',
            name='details',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
