# Generated by Django 5.0.2 on 2024-03-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_hoodie_options_remove_hoodie_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoodie',
            name='avaiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hoodie',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
