# Generated by Django 5.0.2 on 2024-03-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_hoodie_avaiable_alter_hoodie_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='hoodie',
            name='size',
        ),
        migrations.AddField(
            model_name='hoodie',
            name='size',
            field=models.ManyToManyField(to='products.size'),
        ),
    ]
