# Generated by Django 5.0.2 on 2024-03-03 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_size_remove_hoodie_size_hoodie_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoodie',
            name='avaiable',
        ),
        migrations.RemoveField(
            model_name='hoodie',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='size',
            name='stock',
        ),
        migrations.CreateModel(
            name='HoodieSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('avaiable', models.BooleanField(default=False)),
                ('hoodie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.hoodie')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size')),
            ],
        ),
    ]
