# Generated by Django 5.0.2 on 2024-03-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_hoodie_avaiable_remove_hoodie_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoodiesize',
            old_name='avaiable',
            new_name='available',
        ),
        migrations.RemoveField(
            model_name='hoodie',
            name='size',
        ),
    ]
